import { StyleSheet, Dimensions } from "react-native";

const { width: SCREEN_WIDTH } = Dimensions.get("window");

// Colors matching the design: bright blue (#4A90E2), sand/beige (#F5E6D3), white
export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  backgroundGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  scrollView: {
    flex: 1,
  },
  backgroundContainer: {
    minHeight: "100%",
    width: "100%",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    height: 320,
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 40,
    minHeight: "100%",
  },
  header: {
    marginBottom: 32,
    paddingTop: 60,
  },
  subtitle: {
    fontSize: 14,
    color: "rgba(255, 255, 255, 0.85)",
    lineHeight: 20,
    fontWeight: "400",
    letterSpacing: 0.3,
    textAlign: "center",
  },
  formCard: {
    backgroundColor: "#2A2A2A",
    borderRadius: 28,
    padding: 28,
    marginTop: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 1,
    borderColor: "#3A3A3A",
  },
  labelContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
    marginTop: 20,
  },
  label: {
    fontSize: 15,
    fontWeight: "600",
    color: "#FFFFFF",
    letterSpacing: 0.2,
  },
  dateInput: {
    borderWidth: 1.5,
    borderColor: "#3A3A3A",
    borderRadius: 18,
    padding: 18,
    marginBottom: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#1A1A1A",
  },
  dateText: {
    fontSize: 16,
    color: "#FFFFFF",
    fontWeight: "500",
  },
  dateIcon: {
    fontSize: 22,
    color: "#CCCCCC",
  },
  input: {
    borderWidth: 1.5,
    borderColor: "#3A3A3A",
    borderRadius: 18,
    padding: 18,
    marginBottom: 20,
    fontSize: 16,
    color: "#FFFFFF",
    backgroundColor: "#1A1A1A",
  },
  budgetContainer: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 20,
  },
  budgetInput: {
    flex: 1,
    borderWidth: 1.5,
    borderColor: "#3A3A3A",
    borderRadius: 18,
    padding: 18,
    fontSize: 16,
    color: "#FFFFFF",
    backgroundColor: "#1A1A1A",
  },
  currencySelector: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1.5,
    borderColor: "#3A3A3A",
    borderRadius: 18,
    paddingHorizontal: 18,
    paddingVertical: 18,
    backgroundColor: "#1A1A1A",
    minWidth: 100,
    gap: 8,
  },
  currencyText: {
    fontSize: 16,
    color: "#FFFFFF",
    fontWeight: "600",
  },
  currencyDropdown: {
    marginTop: -16,
    marginBottom: 20,
    backgroundColor: "#2A2A2A",
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: "#3A3A3A",
    maxHeight: 300,
    overflow: "hidden",
  },
  currencyOption: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#3A3A3A",
  },
  currencyOptionSelected: {
    backgroundColor: "#3A3A3A",
  },
  currencyOptionText: {
    fontSize: 15,
    color: "#CCCCCC",
  },
  currencyOptionTextSelected: {
    color: "#4A90E2",
    fontWeight: "600",
  },
  button: {
    marginTop: 24,
    borderRadius: 18,
    paddingVertical: 6,
    backgroundColor: "#000000",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  buttonText: {
    fontSize: 17,
    fontWeight: "700",
    color: "#FFFFFF",
    letterSpacing: 0.5,
  },
  loadingContainer: {
    alignItems: "center",
    marginTop: 24,
  },
  loadingText: {
    marginTop: 12,
    color: "#CCCCCC",
    fontSize: 14,
    textAlign: "center",
  },
  errorCard: {
    marginTop: 20,
    backgroundColor: "#3A2A2A",
    borderRadius: 18,
    padding: 18,
    borderWidth: 1.5,
    borderColor: "#5A3A3A",
  },
  errorTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FF6B6B",
    marginBottom: 8,
  },
  errorText: {
    fontSize: 14,
    color: "#FF6B6B",
    fontWeight: "500",
  },
  currencyHint: {
    color: "#CCCCCC",
    marginTop: -12,
    marginBottom: 16,
    marginLeft: 20,
    fontSize: 13,
    fontWeight: "500",
  },
  iosPickerButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: "#2A2A2A",
    borderTopWidth: 1,
    borderTopColor: "#3A3A3A",
    borderRadius: 12,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  headerContainer: {
    position: "absolute",
    top: 50,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    zIndex: 10,
  },
  logoutButton: {
    backgroundColor: "rgba(26, 26, 26, 0.95)",
    borderRadius: 22,
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  backButtonPlaceholder: {
    width: 44,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: "#FFFFFF",
    letterSpacing: -1,
    textShadowColor: "rgba(74, 144, 226, 0.3)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    flex: 1,
    textAlign: "center",
  },
});
