import { StyleSheet } from "react-native";

export const tabStyles = StyleSheet.create({
  container: {
    flexDirection: "row",
    backgroundColor: "#1A1A1A",
    marginHorizontal: 20,
    marginTop: 16,
    marginBottom: 16,
    borderRadius: 20,
    padding: 5,
    paddingHorizontal: 10,
    minHeight: 50,
    borderWidth: 1,
    borderColor: "#2A2A2A",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 2,
    justifyContent: "space-between",
    alignItems: "center",
    gap: 2,
  },
  containerExpanded: {
    padding: 5,
    paddingHorizontal: 15,
    minHeight: 50,
  },
  containerMinimized: {
    padding: 4,
    paddingHorizontal: 5,
    minHeight: 40,
    marginTop: 12,
    marginBottom: 8,
  },
  tab: {
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    paddingHorizontal: 4,
    borderRadius: 14,
    minHeight: 38,
  },
  tabExpanded: {
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  tabMinimized: {
    paddingVertical: 6,
    paddingHorizontal: 3,
    minHeight: 32,
  },
  activeTab: {
    width: 70,
    backgroundColor: "#2A2A2A",
    shadowColor: "#4A90E2",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
    borderWidth: 1.3,
    borderColor: "#4A90E2",
  },
});
