import { StyleSheet } from "react-native";

export const historyStyles = StyleSheet.create({
  container: {
    marginTop: 0,
    marginBottom: 24,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#3A3A3A",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    paddingHorizontal: 0,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  title: {
    fontSize: 18,
    fontWeight: "700",
    color: "#FFFFFF",
    letterSpacing: -0.3,
  },
  clearButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: "#3A3A3A",
  },
  clearText: {
    fontSize: 13,
    color: "#CCCCCC",
    fontWeight: "600",
  },
  scrollView: {
    marginHorizontal: 0,
  },
  scrollContent: {
    paddingHorizontal: 0,
    gap: 14,
    paddingRight: 4,
  },
  card: {
    backgroundColor: "#2A2A2A",
    borderRadius: 20,
    padding: 18,
    width: 220,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    position: "relative",
    borderWidth: 1,
    borderColor: "#3A3A3A",
  },
  removeButton: {
    position: "absolute",
    top: 12,
    right: 12,
    zIndex: 10,
    backgroundColor: "rgba(42, 42, 42, 0.9)",
    borderRadius: 12,
    padding: 4,
  },
  cardContent: {
    gap: 10,
    marginTop: 4,
  },
  destinationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
  },
  destination: {
    fontSize: 17,
    fontWeight: "700",
    color: "#FFFFFF",
    flex: 1,
    letterSpacing: -0.3,
  },
  datesRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  dateText: {
    fontSize: 13,
    color: "#CCCCCC",
    fontWeight: "500",
  },
  budgetRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#3A3A3A",
  },
  budgetText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#4A90E2",
  },
  loadingText: {
    fontSize: 14,
    color: "#CCCCCC",
    textAlign: "center",
    paddingVertical: 16,
    fontWeight: "500",
  },
  emptyText: {
    fontSize: 14,
    color: "#999999",
    textAlign: "center",
    paddingVertical: 20,
    fontStyle: "italic",
    fontWeight: "400",
  },
});

