import { StyleSheet, Dimensions } from "react-native";

const { height: SCREEN_HEIGHT } = Dimensions.get("window");
const MAP_HEIGHT_COLLAPSED = 150; // Small map when collapsed
const MAP_HEIGHT_EXPANDED = SCREEN_HEIGHT * 0.4; // Medium map when expanded (reduced from 0.6)
const LIST_HEIGHT = SCREEN_HEIGHT * 0.6; // Increased from 0.45

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    paddingTop: 50,
    paddingBottom: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 0,
  },
  backButton: {
    marginRight: 16,
  },
  backButtonText: {
    fontSize: 24,
    color: "#000000",
  },
  headerContent: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#000000",
    textAlign: "center",
  },
  mapContainer: {
    backgroundColor: "#E5E5E5",
    position: "relative",
  },
  map: {
    flex: 1,
  },
  mapCollapsedOverlay: {
    position: "absolute",
    bottom: 12,
    right: 12,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 12,
    gap: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    zIndex: 10,
  },
  mapClickableOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "transparent",
    zIndex: 5,
  },
  routeInfoBanner: {
    position: "absolute",
    top: 12,
    left: 12,
    right: 12,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: 12,
    padding: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    zIndex: 10,
  },
  routeInfoContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  routeInfoText: {
    flex: 1,
    fontSize: 14,
    fontWeight: "600",
    color: "#000000",
  },
  clearRouteButton: {
    padding: 4,
  },
  listContainer: {
    backgroundColor: "#FFFFFF",
    flex: 1,
  },
  listContainerMinimized: {
    flex: 0,
    paddingBottom: 0,
    minHeight: 0,
  },
  tabsOnlyContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "transparent",
    paddingBottom: 20,
  },
  segmentedButtons: {
    marginHorizontal: 15,
    marginTop: 10,
    marginBottom: 10,
  },
  tabContent: {
    flex: 1,
    paddingHorizontal: 15,
    paddingTop: 10,
  },
  // Destination Card Styles
  destinationCard: {
    marginBottom: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: "#4A90E2",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  expandedCard: {
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 12,
  },
  destinationImageContainer: {
    width: "100%",
    height: 220,
    position: "relative",
  },
  destinationImage: {
    width: "100%",
    height: "100%",
  },
  orderBadgeOverlay: {
    position: "absolute",
    top: 16,
    left: 16,
  },
  orderBadge: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#4A90E2",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  orderText: {
    color: "#FFFFFF",
    fontWeight: "bold",
    fontSize: 20,
  },
  destinationCardContent: {
    padding: 20,
  },
  destinationHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  destinationInfo: {
    flex: 1,
  },
  destinationTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#000000",
    marginBottom: 8,
  },
  destinationMeta: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  metaItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  metaText: {
    fontSize: 14,
    color: "#666666",
  },
  priceText: {
    fontSize: 14,
    color: "#4A90E2",
    fontWeight: "600",
  },
  divider: {
    marginVertical: 16,
    backgroundColor: "#E0E0E0",
  },
  destinationDescription: {
    fontSize: 16,
    color: "#666666",
    lineHeight: 24,
    marginBottom: 16,
  },
  ticketButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#4A90E2",
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 20,
    gap: 8,
  },
  ticketButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  // Hotel Card Styles
  hotelCard: {
    marginBottom: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: "#4A90E2",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  selectedHotelCard: {
    borderWidth: 3,
    borderColor: "#4A90E2",
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 12,
  },
  hotelImageContainer: {
    width: "100%",
    height: 200,
    position: "relative",
  },
  hotelImage: {
    width: "100%",
    height: "100%",
  },
  hotelRadioOverlay: {
    position: "absolute",
    top: 16,
    right: 16,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    borderRadius: 20,
    padding: 4,
  },
  hotelCardContent: {
    padding: 20,
  },
  hotelName: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#000000",
    marginBottom: 8,
  },
  hotelDescription: {
    fontSize: 15,
    color: "#666666",
    lineHeight: 22,
    marginBottom: 12,
  },
  hotelPriceContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#F5E6D3",
    padding: 12,
    borderRadius: 12,
    marginBottom: 12,
  },
  hotelPrice: {
    fontSize: 16,
    fontWeight: "600",
    color: "#4A90E2",
  },
  bookingLinksContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 12,
  },
  bookingButton: {
    backgroundColor: "#4A90E2",
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  bookingButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  // Restaurant Card Styles
  restaurantCard: {
    marginBottom: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: "#4A90E2",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  restaurantImageContainer: {
    width: "100%",
    height: 220,
    position: "relative",
  },
  restaurantImage: {
    width: "100%",
    height: "100%",
  },
  ratingBadge: {
    position: "absolute",
    top: 16,
    right: 16,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 12,
    gap: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  ratingText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#FFA500",
  },
  restaurantCardContent: {
    padding: 20,
  },
  restaurantName: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#000000",
    marginBottom: 12,
  },
  restaurantMeta: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 12,
  },
  cuisineBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F5E6D3",
    borderRadius: 16,
    paddingVertical: 6,
    paddingHorizontal: 12,
    gap: 6,
  },
  cuisineText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#4A90E2",
  },
  priceRangeContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  priceRange: {
    fontSize: 14,
    color: "#666666",
    fontWeight: "500",
  },
  restaurantDescription: {
    fontSize: 15,
    color: "#666666",
    lineHeight: 22,
    marginBottom: 16,
  },
  websiteButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F5E6D3",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    gap: 8,
    borderWidth: 2,
    borderColor: "#4A90E2",
  },
  websiteButtonText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#4A90E2",
  },
  // Legacy styles (for compatibility)
  placeholderImage: {
    width: "100%",
    height: 220,
    backgroundColor: "#F5E6D3",
    justifyContent: "center",
    alignItems: "center",
  },
  placeholderText: {
    fontSize: 48,
  },
  destinationHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  durationText: {
    color: "#666666",
  },
  coordinatesContainer: {
    display: "none", // Hidden coordinates
  },
  coordinatesLabel: {
    display: "none",
  },
  coordinatesText: {
    display: "none",
  },
  popupCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 12,
    width: 200,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  popupImage: {
    width: "100%",
    height: 100,
    borderRadius: 8,
    marginBottom: 8,
  },
  popupTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#000000",
    marginBottom: 4,
  },
  popupSubtitle: {
    fontSize: 12,
    color: "#666666",
    marginBottom: 8,
  },
  popupRating: {
    fontSize: 12,
    color: "#FFA500",
    marginBottom: 4,
  },
  popupPrice: {
    fontSize: 14,
    fontWeight: "600",
    color: "#000000",
    marginBottom: 8,
  },
  popupButton: {
    backgroundColor: "#4A90E2",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  popupButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  daySection: {
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  dayTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#000000",
    marginBottom: 16,
  },
  dayCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    marginBottom: 12,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  dayCardImage: {
    width: "100%",
    height: 120,
  },
  dayCardContent: {
    padding: 16,
  },
  dayCardType: {
    fontSize: 12,
    fontWeight: "600",
    color: "#666666",
    textTransform: "uppercase",
    marginBottom: 8,
    letterSpacing: 1,
  },
  dayCardTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#000000",
    marginBottom: 8,
  },
  dayCardDescription: {
    fontSize: 14,
    color: "#666666",
    lineHeight: 20,
  },
});

export const getMarkerColor = (visitOrder: number): string => {
  const colors = [
    "#FF6B6B",
    "#4ECDC4",
    "#45B7D1",
    "#FFA07A",
    "#98D8C8",
    "#F7DC6F",
    "#BB8FCE",
    "#85C1E2",
  ];
  return colors[(visitOrder - 1) % colors.length];
};
