import { StyleSheet, Dimensions } from "react-native";

const { height: SCREEN_HEIGHT } = Dimensions.get("window");
const MAP_HEIGHT_COLLAPSED = 150; // Small map when collapsed
const MAP_HEIGHT_EXPANDED = SCREEN_HEIGHT * 0.4; // Medium map when expanded (reduced from 0.6)
const LIST_HEIGHT = SCREEN_HEIGHT * 0.6; // Increased from 0.45

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1A1A1A",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1A1A1A",
    paddingTop: 50,
    paddingBottom: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 0,
  },
  backButton: {
    marginRight: 16,
  },
  backButtonText: {
    fontSize: 24,
    color: "#FFFFFF",
  },
  headerContent: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#FFFFFF",
    textAlign: "center",
  },
  mapContainer: {
    backgroundColor: "#2A2A2A",
    position: "relative",
  },
  map: {
    flex: 1,
  },
  mapCollapsedOverlay: {
    position: "absolute",
    bottom: 12,
    right: 12,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(26, 26, 26, 0.95)",
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 12,
    gap: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    zIndex: 10,
  },
  mapClickableOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "transparent",
    zIndex: 5,
  },
  mapBackButton: {
    position: "absolute",
    top: 12,
    left: 12,
    backgroundColor: "#1A1A1A",
    borderRadius: 22,
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 10,
    zIndex: 100,
    borderWidth: 2,
    borderColor: "#4A90E2",
  },
  routeInfoBanner: {
    position: "absolute",
    top: 12,
    left: 12,
    right: 12,
    backgroundColor: "rgba(26, 26, 26, 0.95)",
    borderRadius: 12,
    padding: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    zIndex: 10,
  },
  routeInfoContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  routeInfoText: {
    flex: 1,
    fontSize: 14,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  clearRouteButton: {
    padding: 4,
  },
  listContainer: {
    backgroundColor: "#1A1A1A",
    flex: 1,
  },
  listContainerMinimized: {
    flex: 0,
    paddingBottom: 0,
    minHeight: 0,
  },
  tabsOnlyContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "transparent",
    paddingBottom: 20,
  },
  segmentedButtons: {
    marginHorizontal: 15,
    marginTop: 10,
    marginBottom: 10,
  },
  tabContent: {
    flex: 1,
    paddingHorizontal: 15,
    paddingTop: 10,
  },
  // Destination Card Styles - Modern Design
  destinationCard: {
    marginBottom: 16,
    backgroundColor: "#2A2A2A",
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 0,
  },
  expandedCard: {
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
  },
  destinationCardWrapper: {
    overflow: "hidden",
    borderRadius: 20,
  },
  destinationImageContainer: {
    width: "100%",
    height: 180,
    position: "relative",
    backgroundColor: "#3A3A3A",
  },
  destinationImage: {
    width: "100%",
    height: "100%",
  },
  imageOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "space-between",
    padding: 12,
  },
  orderBadgeOverlay: {
    alignSelf: "flex-start",
  },
  orderBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(42, 42, 42, 0.98)",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 5,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  orderText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 16,
  },
  priceOverlay: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    borderRadius: 12,
    paddingVertical: 6,
    paddingHorizontal: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  priceOverlayText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  destinationCardContent: {
    padding: 16,
    paddingTop: 14,
  },
  destinationHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  destinationInfo: {
    flex: 1,
  },
  destinationTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#FFFFFF",
    marginBottom: 8,
    letterSpacing: -0.5,
  },
  destinationMeta: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  metaItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#3A3A3A",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
  },
  metaText: {
    fontSize: 14,
    color: "#CCCCCC",
    fontWeight: "500",
  },
  priceText: {
    fontSize: 15,
    color: "#4A90E2",
    fontWeight: "700",
  },
  divider: {
    marginVertical: 12,
    backgroundColor: "#3A3A3A",
    height: 1,
  },
  destinationDescription: {
    fontSize: 14,
    color: "#CCCCCC",
    lineHeight: 20,
    marginBottom: 12,
    letterSpacing: 0.2,
  },
  ticketButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#000000",
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 24,
    gap: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  ticketButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  // Hotel Card Styles - Modern Design
  hotelCard: {
    marginBottom: 12,
    backgroundColor: "#2A2A2A",
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 0,
  },
  hotelCardWrapper: {
    overflow: "hidden",
    borderRadius: 16,
  },
  selectedHotelCard: {
    borderWidth: 2,
    borderColor: "#4A90E2",
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  hotelImageContainer: {
    width: "100%",
    height: 120,
    position: "relative",
    backgroundColor: "#3A3A3A",
  },
  hotelImage: {
    width: "100%",
    height: "100%",
  },
  hotelImageOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "space-between",
    padding: 10,
  },
  hotelRadioOverlay: {
    alignSelf: "flex-end",
    backgroundColor: "rgba(42, 42, 42, 0.98)",
    borderRadius: 20,
    padding: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  hotelPriceOverlay: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    borderRadius: 12,
    paddingVertical: 6,
    paddingHorizontal: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  hotelPriceOverlayText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  hotelPriceOverlaySubtext: {
    color: "rgba(255, 255, 255, 0.8)",
    fontSize: 11,
    fontWeight: "500",
    marginTop: 2,
  },
  hotelCardContent: {
    padding: 12,
    paddingTop: 10,
  },
  hotelName: {
    fontSize: 18,
    fontWeight: "700",
    color: "#FFFFFF",
    marginBottom: 6,
    letterSpacing: -0.5,
  },
  hotelDescription: {
    fontSize: 13,
    color: "#CCCCCC",
    lineHeight: 18,
    marginBottom: 10,
    letterSpacing: 0.2,
  },
  hotelPriceContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#3A3A3A",
    padding: 8,
    borderRadius: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#4A4A4A",
  },
  hotelPrice: {
    fontSize: 16,
    fontWeight: "700",
    color: "#4A90E2",
  },
  bookingLinksContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  bookingButton: {
    backgroundColor: "#000000",
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  bookingButtonText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  // Restaurant Card Styles - Modern Design
  restaurantCard: {
    marginBottom: 12,
    backgroundColor: "#2A2A2A",
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 0,
  },
  restaurantCardWrapper: {
    overflow: "hidden",
    borderRadius: 16,
  },
  restaurantImageContainer: {
    width: "100%",
    height: 120,
    position: "relative",
    backgroundColor: "#3A3A3A",
  },
  restaurantImage: {
    width: "100%",
    height: "100%",
  },
  restaurantImageOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "flex-start",
    alignItems: "flex-end",
    padding: 10,
  },
  ratingBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(42, 42, 42, 0.98)",
    borderRadius: 16,
    paddingVertical: 6,
    paddingHorizontal: 12,
    gap: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  ratingText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#4A90E2",
  },
  restaurantCardContent: {
    padding: 12,
    paddingTop: 10,
  },
  restaurantName: {
    fontSize: 18,
    fontWeight: "700",
    color: "#FFFFFF",
    marginBottom: 8,
    letterSpacing: -0.5,
  },
  restaurantMeta: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 8,
  },
  cuisineBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#3A3A3A",
    borderRadius: 12,
    paddingVertical: 6,
    paddingHorizontal: 12,
    gap: 5,
    borderWidth: 1,
    borderColor: "#4A4A4A",
  },
  cuisineText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  priceRangeContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#3A3A3A",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#4A4A4A",
  },
  priceRange: {
    fontSize: 12,
    color: "#CCCCCC",
    fontWeight: "600",
  },
  restaurantDescription: {
    fontSize: 13,
    color: "#CCCCCC",
    lineHeight: 18,
    marginBottom: 10,
    letterSpacing: 0.2,
  },
  websiteButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#000000",
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 16,
    gap: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  websiteButtonText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#FFFFFF",
    letterSpacing: 0.3,
  },
  // Legacy styles (for compatibility)
  placeholderImage: {
    width: "100%",
    height: 220,
    backgroundColor: "#3A3A3A",
    justifyContent: "center",
    alignItems: "center",
  },
  placeholderText: {
    fontSize: 48,
  },
  destinationHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  durationText: {
    color: "#FFFFFF",
  },
  coordinatesContainer: {
    display: "none", // Hidden coordinates
  },
  coordinatesLabel: {
    display: "none",
  },
  coordinatesText: {
    display: "none",
  },
  popupCard: {
    backgroundColor: "#2A2A2A",
    borderRadius: 12,
    padding: 12,
    width: 200,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    borderWidth: 1,
    borderColor: "#3A3A3A",
  },
  popupImage: {
    width: "100%",
    height: 100,
    borderRadius: 8,
    marginBottom: 8,
  },
  popupTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
    marginBottom: 4,
  },
  popupSubtitle: {
    fontSize: 12,
    color: "#CCCCCC",
    marginBottom: 8,
  },
  popupRating: {
    fontSize: 12,
    color: "#4A90E2",
    marginBottom: 4,
  },
  popupPrice: {
    fontSize: 14,
    fontWeight: "600",
    color: "#FFFFFF",
    marginBottom: 8,
  },
  popupButton: {
    backgroundColor: "#4A90E2",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  popupButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  daySection: {
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  dayTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#FFFFFF",
    marginBottom: 16,
  },
  dayCard: {
    backgroundColor: "#2A2A2A",
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  dayCardImage: {
    width: "100%",
    height: 120,
  },
  dayCardContent: {
    padding: 16,
  },
  dayCardType: {
    fontSize: 12,
    fontWeight: "600",
    color: "#CCCCCC",
    textTransform: "uppercase",
    marginBottom: 8,
    letterSpacing: 1,
  },
  dayCardTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#FFFFFF",
    marginBottom: 8,
  },
  dayCardDescription: {
    fontSize: 14,
    color: "#CCCCCC",
    lineHeight: 20,
  },
});

export const getMarkerColor = (visitOrder: number): string => {
  const colors = [
    "#FF6B6B",
    "#4ECDC4",
    "#45B7D1",
    "#FFA07A",
    "#98D8C8",
    "#F7DC6F",
    "#BB8FCE",
    "#85C1E2",
  ];
  return colors[(visitOrder - 1) % colors.length];
};
